# FIXED
non-circular.obj: ../non-circular.c
non-circular.obj: C:/EEE/CCStudio4.1/ccsv4/tools/compiler/c6000/include/stdlib.h
non-circular.obj: C:/EEE/CCStudio4.1/ccsv4/tools/compiler/c6000/include/linkage.h
non-circular.obj: C:/EEE/CCStudio4.1/ccsv4/tools/compiler/c6000/include/stdio.h
non-circular.obj: C:/EEE/CCStudio4.1/ccsv4/tools/compiler/c6000/include/stdarg.h
non-circular.obj: H:/RTDSP/lab4/RTDSP/Debug/dsp_bios_cfg.h
non-circular.obj: C:/EEE/CCStudio4.1/bios_5_41_02_14/packages/ti/bios/include/std.h
non-circular.obj: C:/EEE/CCStudio4.1/bios_5_41_02_14/packages/ti/bios/include/tistdtypes.h
non-circular.obj: C:/EEE/CCStudio4.1/bios_5_41_02_14/packages/ti/bios/include/hst.h
non-circular.obj: C:/EEE/CCStudio4.1/bios_5_41_02_14/packages/ti/bios/include/pip.h
non-circular.obj: C:/EEE/CCStudio4.1/ccsv4/tools/compiler/c6000/include/stddef.h
non-circular.obj: C:/EEE/CCStudio4.1/bios_5_41_02_14/packages/ti/bios/include/fxn.h
non-circular.obj: C:/EEE/CCStudio4.1/bios_5_41_02_14/packages/ti/bios/include/sts.h
non-circular.obj: C:/EEE/CCStudio4.1/bios_5_41_02_14/packages/ti/bios/include/swi.h
non-circular.obj: C:/EEE/CCStudio4.1/bios_5_41_02_14/packages/ti/bios/include/hwi.h
non-circular.obj: C:/EEE/CCStudio4.1/bios_5_41_02_14/packages/ti/bios/include/tsk.h
non-circular.obj: C:/EEE/CCStudio4.1/ccsv4/tools/compiler/c6000/include/stdarg.h
non-circular.obj: C:/EEE/CCStudio4.1/ccsv4/tools/compiler/c6000/include/stddef.h
non-circular.obj: C:/EEE/CCStudio4.1/bios_5_41_02_14/packages/ti/bios/include/knl.h
non-circular.obj: C:/EEE/CCStudio4.1/bios_5_41_02_14/packages/ti/bios/include/atm.h
non-circular.obj: C:/EEE/CCStudio4.1/bios_5_41_02_14/packages/ti/bios/include/que.h
non-circular.obj: C:/EEE/CCStudio4.1/bios_5_41_02_14/packages/ti/bios/include/mem.h
non-circular.obj: C:/EEE/CCStudio4.1/ccsv4/tools/compiler/c6000/include/stddef.h
non-circular.obj: C:/EEE/CCStudio4.1/ccsv4/tools/compiler/c6000/include/stdarg.h
non-circular.obj: C:/EEE/CCStudio4.1/bios_5_41_02_14/packages/ti/bios/include/prd.h
non-circular.obj: C:/EEE/CCStudio4.1/bios_5_41_02_14/packages/ti/bios/include/sem.h
non-circular.obj: C:/EEE/CCStudio4.1/bios_5_41_02_14/packages/ti/bios/include/obj.h
non-circular.obj: C:/EEE/CCStudio4.1/ccsv4/tools/compiler/c6000/include/stddef.h
non-circular.obj: C:/EEE/CCStudio4.1/bios_5_41_02_14/packages/ti/bios/include/sys.h
non-circular.obj: C:/EEE/CCStudio4.1/ccsv4/tools/compiler/c6000/include/stdarg.h
non-circular.obj: C:/EEE/CCStudio4.1/bios_5_41_02_14/packages/ti/bios/include/trg.h
non-circular.obj: C:/EEE/CCStudio4.1/ccsv4/tools/compiler/c6000/include/stddef.h
non-circular.obj: C:/EEE/CCStudio4.1/bios_5_41_02_14/packages/ti/bios/include/_hook.h
non-circular.obj: C:/EEE/CCStudio4.1/bios_5_41_02_14/packages/ti/bios/include/log.h
non-circular.obj: C:/EEE/CCStudio4.1/bios_5_41_02_14/packages/ti/bios/include/_log.h
non-circular.obj: C:/EEE/CCStudio4.1/bios_5_41_02_14/packages/ti/bios/include/trc.h
non-circular.obj: C:/EEE/CCStudio4.1/ccsv4/C6000/dsk6713/include/dsk6713.h
non-circular.obj: C:/EEE/CCStudio4.1/ccsv4/C6000/csl/include/csl.h
non-circular.obj: C:/EEE/CCStudio4.1/ccsv4/C6000/csl/include/csl_chip.h
non-circular.obj: C:/EEE/CCStudio4.1/ccsv4/C6000/csl/include/csl_stdinc.h
non-circular.obj: C:/EEE/CCStudio4.1/ccsv4/C6000/csl/include/csl_stdinchal.h
non-circular.obj: C:/EEE/CCStudio4.1/ccsv4/C6000/csl/include/tistdtypes.h
non-circular.obj: C:/EEE/CCStudio4.1/ccsv4/C6000/csl/include/csl_chiphal.h
non-circular.obj: C:/EEE/CCStudio4.1/ccsv4/C6000/csl/include/csl_emifhal.h
non-circular.obj: C:/EEE/CCStudio4.1/ccsv4/C6000/csl/include/csl_chip.h
non-circular.obj: C:/EEE/CCStudio4.1/ccsv4/C6000/csl/include/csl_irq.h
non-circular.obj: C:/EEE/CCStudio4.1/ccsv4/C6000/csl/include/csl_irqhal.h
non-circular.obj: C:/EEE/CCStudio4.1/ccsv4/C6000/csl/include/csl_timer.h
non-circular.obj: C:/EEE/CCStudio4.1/ccsv4/C6000/csl/include/csl_timerhal.h
non-circular.obj: C:/EEE/CCStudio4.1/ccsv4/C6000/dsk6713/include/dsk6713_aic23.h
non-circular.obj: C:/EEE/CCStudio4.1/ccsv4/C6000/csl/include/csl_mcbsp.h
non-circular.obj: C:/EEE/CCStudio4.1/ccsv4/C6000/csl/include/csl_mcbsphal.h
non-circular.obj: C:/EEE/CCStudio4.1/ccsv4/tools/compiler/c6000/include/math.h
non-circular.obj: C:/EEE/CCStudio4.1/ccsv4/tools/compiler/c6000/include/float.h
non-circular.obj: C:/EEE/CCStudio4.1/ccsv4/tools/compiler/c6000/include/access.h
non-circular.obj: C:/EEE/CCStudio4.1/ccsv4/tools/compiler/c6000/include/mathf.h
non-circular.obj: C:/EEE/CCStudio4.1/ccsv4/tools/compiler/c6000/include/unaccess.h
non-circular.obj: C:/EEE/CCStudio4.1/ccsv4/tools/compiler/c6000/include/mathl.h
non-circular.obj: C:/EEE/CCStudio4.1/ccsv4/tools/compiler/c6000/include/unaccess.h
non-circular.obj: C:/EEE/CCStudio4.1/ccsv4/C6000/dsk6713/include/helper_functions_ISR.h
non-circular.obj: C:/EEE/CCStudio4.1/ccsv4/tools/compiler/c6000/include/math.h
non-circular.obj: ../fir_coef.txt
